package main;
/*
 * This Java source file was generated by the Gradle 'init' task.
 */


import java.util.concurrent.ExecutionException;

import producer.Producer;
import personObject.Person;



public class App {
    public String getGreeting() {
        return "Hello World!";
    }

    public static void main(String[] args) throws ExecutionException, InterruptedException {
        System.out.println(new App().getGreeting());
        
        String bootstrapServers="master:9092";
        String topic="test_java";

        Producer producer=new Producer(bootstrapServers);

        // long start_sync=System.nanoTime();
        // for (int i=0;i<100000;i++){
        //     Person person=new Person();
        //     producer.put_sync(topic,i,person);
        // }
        // long end_sync=System.nanoTime();


        long start_async=System.nanoTime();
        for (int i=0;i<2000000;i++){
            Person person=new Person();
            producer.put_async(topic,i,person);
        }      
        long end_async=System.nanoTime();
        // System.out.println("Synchronous time: "+(end_sync-start_sync));
        System.out.println("ASynchronous time: "+(end_async-start_async));  
        producer.close();
        
    }
}
